language: r
cache: packages
sudo: false

os:
  - linux
  - osx

r_packages:
  - xml2
  - covr

after_success:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then echo 'covr::coveralls(quiet=FALSE)' | R --vanilla; fi
